AWSTemplateFormatVersion: 2010-09-09
Description: Test Raw bucket for data lake as a service - client (DaaS - Client)

# Required Parameters: Environment
Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    Default: dev

# Create Resources
Resources:
  CreateDaaSRawBucket:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Environment: !Sub ${Environment}
        Name: !Sub ${Entity}-s3-${AWS::Region}-daas-client-test-raw-bucket
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-${Environment}/s3/scripts/template/cft-s3-common-template.yml
      TimeoutInMinutes: '60'
