AWSTemplateFormatVersion: 2010-09-09
Description: Metadata Generator Lambda for data lake as a service - client (DaaS - Client)

Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    Default: dev
  LambdaZipFileName:
    Type: String

Resources:
  CreateDaaSMetadataGenLambda:
    Type: 'AWS::CloudFormation::Stack'
    Properties :
      Parameters:
        Environment: !Ref Environment
        Name: !Sub ${Entity}-lmd-metadata-generator-${Environment}
        Description: !Sub Datalake as a Service Client metadata generator deployed in ${Environment}
        LambdaCompressedFileName: !Sub ${LambdaZipFileName}
        HandlerName: lmd-metadata-generator.lambda_handler
        MemorySize: 128
        Timeout: 120
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-${Environment}/lmd/scripts/template/cft-lmd-common-template.yml
      TimeoutInMinutes : '60'

  CreateDaaSGlueClientServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'rle-metadata-generator-service-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - glue.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Path: "/"


  CreateDaaSMetadataGenPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
        - !GetAtt CreateDaaSMetadataGenLambda.Outputs.LambdaRole
      PolicyName: plc-inline-metadata-gen
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "createDaaSGlueServiceLinkedRole"
            Effect: "Allow"
            Action: "iam:CreateServiceLinkedRole"
            Resource: "arn:aws:iam::*:role/aws-service-role/glue.amazonaws.com/AWSGlueServiceRole*"
            Condition:
              StringLike:
                iam:PassedToService:
                      - "glue.amazonaws.com"
          -
            Sid: "allowS3Access"
            Effect: "Allow"
            Action:
              - "s3:GetObject"
            Resource: "*"
          -
            Sid: "allowLambdaInvokeAccess"
            Effect: "Allow"
            Action: "lambda:*"
            Resource: 
              Fn::Sub: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Entity}-lmd-metadata-generator-${Environment}"
          -
            Sid: "allowGlueAccess"
            Effect: "Allow"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "ec2:RunInstances"
              - "logs:CreateLogGroup"
            Resource:
              - "arn:aws:s3:::*/*aws-glue-*/*"
              - "arn:aws:s3:::aws-glue-*"
              - "arn:aws:s3:::aws-glue-*/*"
              - "arn:aws:ec2:*:*:image/*"
              - "arn:aws:ec2:*:*:subnet/*"
              - "arn:aws:ec2:*:*:key-pair/*"
              - "arn:aws:ec2:*:*:instance/*"
              - "arn:aws:ec2:*:*:volume/*"
              - "arn:aws:ec2:*:*:security-group/*"
              - "arn:aws:ec2:*:*:network-interface/*"
              - Fn::Sub: "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
          -
            Sid: "allowGetLogEvents"
            Effect: "Allow"
            Action: "logs:GetLogEvents"
            Resource:
              -  "arn:aws:logs:*:*:*:/aws-glue/*"
          -
            Sid: "passRoleGlueServiceRole"
            Effect: "Allow"
            Action: "iam:PassRole"
            Resource:
              - Fn::Sub: "arn:aws:iam::${AWS::AccountId}:role/rle-daas-client-service-role-${Environment}"
            Condition:
              StringLike:
                iam:PassedToService:
                      - "glue.amazonaws.com"
          -
            Sid: "allowOtherAccess"
            Effect: "Allow"
            Action:
              - "ec2:DescribeInstances"
              - "rds:DescribeDBSubnetGroups"
              - "cloudwatch:GetMetricData"
              - "s3:ListBucket"
              - "ec2:DescribeVpcAttribute"
              - "glue:*"
              - "iam:ListAttachedRolePolicies"
              - "cloudwatch:ListDashboards"
              - "rds:DescribeDBInstances"
              - "iam:ListRolePolicies"
              - "ec2:DescribeKeyPairs"
              - "ec2:DescribeRouteTables"
              - "iam:GetRole"
              - "iam:ListRoles"
              - "s3:GetBucketAcl"
              - "ec2:DescribeSecurityGroups"
              - "cloudformation:GetTemplateSummary"
              - "cloudformation:DescribeStacks"
              - "ec2:DescribeImages"
              - "s3:ListAllMyBuckets"
              - "ec2:DescribeVpcs"
              - "iam:ListUsers"
              - "iam:ListGroups"
              - "ec2:DescribeVpcEndpoints"
              - "ec2:DescribeSubnets"
              - "iam:GetRolePolicy"
              - "s3:GetBucketLocation"
              - "rds:DescribeDBClusters"
            Resource: "*"
