AWSTemplateFormatVersion: 2010-09-09
Description: Glue controller Role to provision crawler and manage partitions for DaaS Client

# Required Parameter: Environment
Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, tst, int, uat, prd, poc]
  AccountId:
    Type: String
    Default: 495430879539

# Resources
Resources:
  CreateRleGlueControlRole:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Environment: !Ref Environment
        Name: !Sub ${Entity}-rle-glue-controller-admin-${Environment}
        AWSTrustPrincipal: !Sub arn:aws:iam::${AccountId}:role/rle-${Entity}-lmd-ingest-invoker-${Environment}
        Description: !Sub Glue controller Role to provision crawler and manage partitions for DaaS Client deployed in ${Environment}
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-${Environment}/rle/scripts/template/cft-rle-common-template.yml
      TimeoutInMinutes: '60'

  CreateRleGlueControlPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
        - !GetAtt CreateRleGlueControlRole.Outputs.RoleName
      PolicyName: plc-inline-glue-controller
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'allowGlueAccess'
            Effect: 'Allow'
            Action:
              - 'glue:GetPartition'
              - 'glue:GetCrawler'
            Resource:
              - '*'
          - Sid: 'allowEventAccess'
            Effect: 'Allow'
            Action:
              - 'event:PutRule'
              - 'event:PutTargets'
            Resource:
              - '*'         
