AWSTemplateFormatVersion: 2010-09-09
Description: Athena log storage for data lake as a service - client (DaaS - Client)

# Required Parameters: Environment
Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, tst, int, qa, uat, prd, poc]

# Create Resources
Resources:
  CreateDaaSRawBucket:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Entity: !Ref Entity      
        Environment: !Sub ${Environment}
        Name: !Sub ${Entity}-s3-${AWS::Region}-daas-client-athena-log
      TemplateURL: ../../daas-common/cft-s3-common-template.yml
      TimeoutInMinutes: '60'
