AWSTemplateFormatVersion: 2010-09-09
Description: VPC for data lake as a service - client (DaaS - Client)

Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
     Type: String
     Default: dev
     AllowedValues: [dev, tst, int, qa, uat, prd, poc]
  Region:
    Type: String
    Default: us-west-2

Resources:
  CreateVPCForDaaS:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Entity: !Ref Entity
        Environment: !Ref Environment
        Name: !Sub ${Entity}-vpc-daas-client-${Environment}
        PrivateSubnet1Cidr: 10.1.0.0/24
        PrivateSubnet2Cidr: 10.1.16.0/24
        PrivateSubnet1AZ: !Sub ${Region}b
        PrivateSubnet2AZ: !Sub ${Region}c
        PublicSubnet1Cidr: 10.1.129.0/24
        PublicSubnet2Cidr: 10.1.145.0/24
        PublicSubnet1AZ: !Sub ${Region}b
        PublicSubnet2AZ: !Sub ${Region}c
        VpcCidrBlock: 10.1.0.0/16
      TemplateURL: ../../daas-common/cft-vpc-common-template.yml
      TimeoutInMinutes: '60'
