AWSTemplateFormatVersion: 2010-09-09
Description: Default Security Group for EC2 in data lake as a service - core (DaaS - Client)

Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
     Type: String
     Default: dev
     AllowedValues: [dev, tst, int, qa, uat, prd, poc]

Resources:
  CreateDfltLmdSgrpForDaaSClient:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Description: Default EC2 secruity group for Daas Client      
        Entity: !Ref Entity
        Environment: !Ref Environment
        Name: !Sub '${Entity}-sgrp-ec2-default-${Environment}'
      TemplateURL: ../../daas-common/cft-sgrp-common-template.yml
      TimeoutInMinutes: '60'
