AWSTemplateFormatVersion: 2010-09-09
Description: DaaS Core Permission Set for Data Engineer

# Required Parameter: Environment
Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, tst, int, uat, prd, poc]

# Resources
Resources:
  CreatePermSetDataEngineer:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Description: !Sub Data Engineer Permission Set for DaaS Core deployed in ${Environment}
        Entity: !Ref Entity
        Environment: !Ref Environment
        Name: !Sub ${Entity}-perm-data-engineer-${Environment}
        PolicyFileName: !Sub stacks/stk-perm-data-engineer/stk-perm-data-engineer-policy.yml
        SessionDuration: PT12H
      TemplateURL: ../../daas-common/cft-rle-common-template.yml
      TimeoutInMinutes: '60'