AWSTemplateFormatVersion: 2010-09-09
Description: NAT Gateway for data lake as a service - core (DaaS - Core)

Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
     Type: String
     Default: dev
     AllowedValues: [dev, tst, int, qa, uat, prd, poc]

Resources:
  CreateNGWForDaaSCore:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Entity: !Ref Entity
        Environment: !Ref Environment
        Name: !Sub '${Entity}-ngw-daas-core-${Environment}'
      TemplateURL: ../../daas-common/cft-ngw-common-template.yml
      TimeoutInMinutes: '60'
