AWSTemplateFormatVersion: 2010-09-09
Description: Fetch the Organization ID for the VPC (DaaS - Core)

Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, tst, int, qa, uat, prd, poc]
  LambdaZipFileName:
    Type: String


Resources:
  CreateDaaSGetOrgIdLambda:
    Type: 'AWS::CloudFormation::Stack'
    Properties :
      Parameters:
        Description: !Sub Helper lambda to get organization id for the vpc in ${Environment}
        EnableVpcConfig: False
        Entity: !Ref Entity
        Environment: !Ref Environment
        HandlerName: setup/lmd-get-organization-id.lambda_handler
        LambdaCompressedFileName: !Sub ${LambdaZipFileName}
        MemorySize: 128
        Name: !Sub ${Entity}-lmd-get-organization-id-${Environment}        
        Timeout: 120
      TemplateURL: ../../daas-common/cft-lmd-common-template.yml
      TimeoutInMinutes : '60'

  CreateDaaSGetOrgIdPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
        - !GetAtt CreateDaaSGetOrgIdLambda.Outputs.LambdaRole
      PolicyName: plc-inline-get-sec-grps
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "allowDaaSGetSecGrpRole"
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Resource: 
              Fn::Sub: "arn:aws:iam::*:role/*-rle-get-organization-id-${Environment}"
          -
            Sid: "allowOrgDescAccess"
            Effect: "Allow"
            Action: 'organizations:DescribeOrganization'
            Resource: "*"
      