AWSTemplateFormatVersion: 2010-09-09
Description: Setup bucket for data lake as a service - Core (DaaS - Core)

# Required Parameters: Environment
Parameters:
  DaasCoreAccountId:
    Type: String
    Default: false
  DaasCoreEntity:
    Type: String
    Default: false
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    Default: dev
  EventQueueArn:
    Type: String
    Default: false

# Create Resources
Resources:
  CreateDaaSCoreSetupBucket:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Entity: !Ref Entity      
        Environment: !Sub ${Environment}
        EventQueueArn: !Ref EventQueueArn    
        Name: !Sub ${Entity}-s3-${AWS::Region}-daas-core-setup-bucket
      TemplateURL: ../../daas-common/cft-s3-common-template.yml
      TimeoutInMinutes: '60'