AWSTemplateFormatVersion: 2010-09-09
Description: Model Generator Lambda for data lake as a service - core (DaaS - Core)

Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, tst, int, uat, prd, poc]
  LambdaZipFileName:
    Type: String

Resources:
  CreateDaaSCoreModelGenLambda:
    Type: 'AWS::CloudFormation::Stack'
    Properties :
      Parameters:
        Description: !Sub Lambda Model Generator for Datalake as a Service deployed in ${Environment}
        Entity: !Ref Entity
        Environment: !Ref Environment
        HandlerName: lmd-curate-model-generator.lambda_handler
        LambdaCompressedFileName: !Sub ${LambdaZipFileName}
        LambdaEnvVarFileName: !Sub stacks/stk-lmd-curate-model-generator/stk-lmd-curate-model-generator-env-var.yml
        MemorySize: 128 
        Name: !Sub ${Entity}-lmd-curate-model-generator-${Environment}
        SqsEventTriggerArn: 
          Fn::ImportValue:
            !Sub "${Entity}-sqs-curate-daas-core-${Environment}-arn"
        Timeout: 120
      TemplateURL: ../../daas-common/cft-lmd-common-template.yml
      TimeoutInMinutes : '60'

  CreateDaaSCoreModelGenPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
        - !GetAtt CreateDaaSCoreModelGenLambda.Outputs.LambdaRole
      PolicyName: plc-inline-lmd-ingest-invk
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "allowS3ReadAccess"
            Effect: "Allow"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
              - "s3:DeleteObjectVersion"
            Resource:
              - "*"
          -
            Sid: "assumeDaaSClientRole"
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Resource: 
              Fn::Sub: "arn:aws:iam::*:role/rle-${Entity}-lmd-metadata-generator-${Environment}"
          -
            Sid: "allowGlueAccess"
            Effect: "Allow"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "ec2:RunInstances"
              - "logs:CreateLogGroup"
            Resource:
              - "arn:aws:s3:::*/*aws-glue-*/*"
              - "arn:aws:s3:::aws-glue-*"
              - "arn:aws:s3:::aws-glue-*/*"
              - "arn:aws:ec2:*:*:image/*"
              - "arn:aws:ec2:*:*:subnet/*"
              - "arn:aws:ec2:*:*:key-pair/*"
              - "arn:aws:ec2:*:*:instance/*"
              - "arn:aws:ec2:*:*:volume/*"
              - "arn:aws:ec2:*:*:security-group/*"
              - "arn:aws:ec2:*:*:network-interface/*"
              - Fn::Sub: "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
          -
            Sid: "allowGetLogEvents"
            Effect: "Allow"
            Action: "logs:GetLogEvents"
            Resource:
              -  "arn:aws:logs:*:*:*:/aws-glue/*"
          -
            Sid: "allowStepFunctionAccess"
            Effect: "Allow"
            Action: "states:StartExecution"
            Resource:
              - "arn:aws:states:*:*:stateMachine:*"
          -
            Sid: "allowOtherAccess"
            Effect: "Allow"
            Action:
              - "ec2:DescribeInstances"
              - "rds:DescribeDBSubnetGroups"
              - "cloudwatch:GetMetricData"
              - "s3:ListBucket"
              - "ec2:DescribeVpcAttribute"
              - "glue:*"
              - "iam:ListAttachedRolePolicies"
              - "cloudwatch:ListDashboards"
              - "rds:DescribeDBInstances"
              - "iam:ListRolePolicies"
              - "ec2:DescribeKeyPairs"
              - "ec2:DescribeRouteTables"
              - "iam:GetRole"
              - "iam:ListRoles"
              - "s3:GetBucketAcl"
              - "ec2:DescribeSecurityGroups"
              - "cloudformation:GetTemplateSummary"
              - "cloudformation:DescribeStacks"
              - "ec2:DescribeImages"
              - "s3:ListAllMyBuckets"
              - "ec2:DescribeVpcs"
              - "iam:ListUsers"
              - "iam:ListGroups"
              - "ec2:DescribeVpcEndpoints"
              - "ec2:DescribeSubnets"
              - "iam:GetRolePolicy"
              - "s3:GetBucketLocation"
              - "rds:DescribeDBClusters"
            Resource: "*"              