AWSTemplateFormatVersion: 2010-09-09
Description: AWS Common SQS Queue Cloudformation Template

Parameters:
  Application:
    Type: String
    Default: daas
  BusinessUnit:
    Type: String
    Default: private
  CostCenter:
    Type: String
    Default: 55100
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    AllowedValues: [dev, tst, int, qa, uat, prd, poc]
  Name:
    Type: String
  QueueType:
    Type: String
    Default: standard
    AllowedValues: [fifo, standard]
  DLQMaxReceiveCount:
    Type: String
    Default: 10
  MaximumMessageSize:
    Type: String
    Default: 262144
  MessageRetentionPeriod:
    Type: String
    Default: 576
  EnableDLQ:
    Type: String
    Default: false
    AllowedValues: [true, false]
  Project:
    Type: String
    Default: daas
  Support:
    Type: String
    Default: nathan.ganesh@gmail.com
  TagsVarFileName:
    Type: String
    Default: template/cft-tag-common-var.yml

Conditions:
  isFifo: !Equals [ !Ref QueueType, 'fifo']
  isDLQEnabled: !Equals [ !Ref EnableDLQ, 'true']

Resources:
  CreateSQSQueueCreation:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: !Sub ${MaximumMessageSize}
      MessageRetentionPeriod: !Sub ${MessageRetentionPeriod}
      QueueName: !If
          - isFifo
          - !Sub ${Name}.${QueueType}
          - !Sub ${Name}
      ReceiveMessageWaitTimeSeconds: 5
      RedrivePolicy: !If
          - isDLQEnabled
          -
            deadLetterTargetArn:
              Fn::GetAtt:
                - "CreateDeadLetterQueue"
                - "Arn"
            maxReceiveCount: !Ref DLQMaxReceiveCount
          - !Ref "AWS::NoValue"
      Fn::Transform:
        Name: AWS::Include
        Parameters:
          Location:
            Fn::Sub: 's3://${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-${Environment}/tag/scripts/${TagsVarFileName}'
      VisibilityTimeout: 120

  CreateDeadLetterQueue:
    Type: AWS::SQS::Queue
    Condition: isDLQEnabled
    Properties:
      QueueName: !If
          - isFifo
          - !Sub ${Name}-dlq.${QueueType}
          - !Sub ${Name}-dlq
      Tags :
          - Key: Application
            Value: !Ref Application
          - Key: CostCenter
            Value: !Ref CostCenter
          - Key: Environment
            Value: !Ref Environment
          - Key: Name
            Value: !Ref Name
          - Key: Project
            Value: !Ref Project
          - Key: Support
            Value: !Ref Support

Outputs:
  SQSQueueName:
    Value: !Ref CreateSQSQueueCreation
    Export:
      Name: !Sub '${Name}'
  S3QueueArn:
    Value: !GetAtt CreateSQSQueueCreation.Arn
    Export:
      Name: !Sub '${Name}-arn'
