AWSTemplateFormatVersion: 2010-09-09
Description: 'NAT Gateway Common CloudFormation Stack'

Parameters:
  Application:
    Type: String
    Default: daas
  BusinessUnit:
    Type: String
    Default: private
  CostCenter:
    Type: String
    Default: personal
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    AllowedValues: [dev, tst, int, uat, prd, poc]
  Name:
    Type: String
    Default: daas-ngw
  Project:
    Type: String
    Default: daas
  Support:
    Type: String
    Default: nathan.ganesh@gmail.com

Resources:
  CreateNATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
        AllocationId: !GetAtt AttachElasticIP.AllocationId
        SubnetId:
          Fn::ImportValue: !Sub 'daas-vpc-${Environment}-public-subnet-1'
        Tags:
          - Key: Application
            Value: !Ref Application
          - Key: BusinessUnit
            Value: !Ref BusinessUnit
          - Key: CostCenter
            Value: !Ref CostCenter
          - Key: Entity
            Value: !Ref Entity
          - Key: Environment
            Value: !Ref Environment
          - Key: Name
            Value: !Ref Entity-ngw
          - Key: Project
            Value: !Ref Project
          - Key: Support
            Value: !Ref Support

  AttachElasticIP:
    Type: AWS::EC2::EIP
    Properties:
        Domain: vpc

  CreateNatGatewayRoute:
    Type: AWS::EC2::Route
    Properties:
        RouteTableId:
          Fn::ImportValue: !Sub 'daas-vpc-${Environment}-private-route-table-1'
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId: !Ref CreateNATGateway

Outputs:
  NgwStackName:
    Description: NGW Stack Name
    Value: !Sub '${AWS::StackName}'
    Export:
      Name: !Sub '${Entity}-ngw-stack-name'
  Ngw:
    Description: Ngw
    Value: !Ref CreateNATGateway
    Export:
      Name: !Sub '${Entity}-ngw'
  NgwIpAddress:
    Description: NAT Gateway public IP Address
    Value: !Ref AttachElasticIP
    Export:
      Name: !Sub '${Entity}-ngw-ip'
