AWSTemplateFormatVersion: 2010-09-09
Description: AWS Common Template for IAM Role.

Parameters:
  Application:
    Type: String
    Default: daas
  BusinessUnit:
    Type: String
    Default: private
  CostCenter:
    Type: String
    Default: 55100
  DaasCoreAccountId:
    Type: String
    Default: false
  DaasCoreEntity:
    Type: String
    Default: false
  Description:
    Type: String    
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    AllowedValues: [dev, tst, int, uat, prd, poc]
  Name:
    Type: String
  Project:
    Type: String
    Default: daas
  Service:
    Type: String   
  Support:
    Type: String
    Default: nathan.ganesh@gmail.com
  TagsVarFileName:
    Type: String
    Default: template/cft-tag-common-var.yml
  TrustPolicyFileName:
    Type: String
    Default: template/cft-rle-common-trust.yml  

Resources:
  CreateRole:
    Type: AWS::IAM::Role
    Properties :
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole        
          Fn::Transform:
            Name: AWS::Include
            Parameters:
              Location:
                Fn::Sub: 's3://${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-${Environment}/rle/scripts/${TrustPolicyFileName}'
      Description: !Sub ${Description}  
      RoleName: !Sub ${Name}
      Tags:
        - Key: Application 
          Value:
            Fn::Sub: ${Application}
        - Key: BusinessUnit
          Value:
            Fn::Sub: ${BusinessUnit}
        - Key: CostCenter
          Value:
            Fn::Sub: ${CostCenter}
        - Key: Entity
          Value:
            Fn::Sub: ${Entity}
        - Key: Environment
          Value:
            Fn::Sub: ${Environment}
        - Key: Name
          Value:
            Fn::Sub: ${Name}
        - Key: Project
          Value:
            Fn::Sub: ${Project}
        - Key: Support
          Value:
            Fn::Sub: ${Support}

Outputs:
  RoleArn:
    Value: !GetAtt CreateRole.Arn
    Export:
      Name: !Sub ${Name}-arn
  RoleName:
    Value: !Ref CreateRole
    Export:
      Name: !Sub ${Name}

