AWSTemplateFormatVersion: 2010-09-09
Description: AWS Common Template for Lambda Layer.

Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
  Name:
    Type: String
  LayerName:
    Type: String

Resources:
  CreateLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties :
      CompatibleRuntimes:
        - python3.9
        - python3.8
        - python3.7
        - python3.6
      Content:
        S3Bucket: !Sub ${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-${Environment}
        S3Key: !Sub lmdlyr/scripts/stacks/stk-lmdlyr-${LayerName}/${LayerName}.zip
      Description: !Sub Lambda Layer for ${LayerName} in ${Environment}
      LayerName: !Sub ${Entity}-lmdlyr-${Name}
      LicenseInfo: MIT
Outputs:
  LambdaLayerArn:
    Value: !Ref CreateLambdaLayer
    Export:
      Name: !Sub ${Entity}-lmdlyr-${Name}-arn
