AWSTemplateFormatVersion: 2010-09-09
Description: AWS Secret Manager Cloudformation Template

Parameters:
  Application:
    Type: String
    Default: daas
  BusinessUnit:
    Type: String
    Default: private
  CostCenter:
    Type: String
    Default: 55100
  Description:
    Type: String
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    AllowedValues: [dev, tst, int, uat, prd, poc]
  Name:
    Type: String
  Project:
    Type: String
    Default: daas
  SecretString:
    Type: String
  Support:
    Type: String
    Default: nathan.ganesh@gmail.com
  TagsVarFileName:
    Type: String
    Default: template/cft-tag-common-var.yml

Resources:
  CreateSecretsManager:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub ${Name}-${Environment}
      Description: !Sub ${Description} for ${Environment}
      SecretString: !Ref SecretString
      Fn::Transform:
        Name: AWS::Include
        Parameters:
          Location:
            Fn::Sub: 's3://${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-${Environment}/tag/scripts/${TagsVarFileName}'

Outputs:
  SecretsManagerName:
    Value: !Ref CreateSecretsManager
    Export:
      Name: !Sub '${Name}-${Environment}'
