AWSTemplateFormatVersion: 2010-09-09
Description: AWS NAT Gateway Common CloudFormation Stack

Parameters:
  Application:
    Type: String
    Default: daas
  BusinessUnit:
    Type: String
    Default: private
  CostCenter:
    Type: String
    Default: personal
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    AllowedValues: [dev, tst, int, uat, prd, poc]
  Name:
    Type: String
    Default: daas-ngw
  Project:
    Type: String
    Default: daas
  Support:
    Type: String
    Default: nathan.ganesh@gmail.com
  TagsVarFileName:
    Type: String
    Default: template/cft-tag-common-var.yml

Resources:
  CreateNATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
        AllocationId: !GetAtt AttachElasticIP.AllocationId
        SubnetId:
          Fn::ImportValue: !Sub '${Entity}-public-subnet-1'
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Fn::Sub: 's3://${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-${Environment}/tag/scripts/${TagsVarFileName}'

  AttachElasticIP:
    Type: AWS::EC2::EIP
    Properties:
        Domain: vpc

  CreateNatGatewayRoute:
    Type: AWS::EC2::Route
    Properties:
        RouteTableId:
          Fn::ImportValue: !Sub '${Entity}-private-route-table-1'
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId: !Ref CreateNATGateway
  
  AssociatePrivSubnet1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
        RouteTableId:
          Fn::ImportValue: !Sub '${Entity}-private-route-table-1'
        SubnetId:
          Fn::ImportValue: !Sub '${Entity}-private-subnet-2'

  AssociatePrivSubnet2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
        RouteTableId:
          Fn::ImportValue: !Sub '${Entity}-private-route-table-1'
        SubnetId:
          Fn::ImportValue: !Sub '${Entity}-private-subnet-1'

Outputs:
  NgwStackName:
    Description: NGW Stack Name
    Value: !Sub '${AWS::StackName}'
    Export:
      Name: !Sub '${Entity}-ngw-stack-name'
  Ngw:
    Description: Ngw
    Value: !Ref CreateNATGateway
    Export:
      Name: !Sub '${Entity}-ngw'
  NgwIpAddress:
    Description: NAT Gateway public IP Address
    Value: !Ref AttachElasticIP
    Export:
      Name: !Sub '${Entity}-ngw-ip'
