AWSTemplateFormatVersion: 2010-09-09
Description: Glue controller Role to provision crawler and manage partitions for DaaS Client

# Required Parameter: Environment
Parameters:
  DaasCoreAccountId:
    Type: String
    Default: false
  DaasCoreEntity:
    Type: String
    Default: false
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, tst, int, qa, uat, prd, poc]

# Resources
Resources:
  CreateRleGlueControlRole:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        DaasCoreAccountId: !Ref DaasCoreAccountId
        DaasCoreEntity: !Ref DaasCoreEntity
        Description: !Sub Glue controller Role to provision crawler and manage partitions for DaaS Client deployed in ${Environment}              
        Entity: !Ref Entity
        Environment: !Ref Environment
        Name: !Sub ${Entity}-rle-ingest-glue-controller-admin-${Environment}
        Service: glue.amazonaws.com
        TrustPolicyFileName: !Sub stacks/stk-rle-ingest-glue-controller-admin/stk-rle-ingest-glue-controller-admin-trust.yml
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-${Environment}/rle/scripts/template/cft-rle-common-template.yml
      TimeoutInMinutes: '60'

  CreateRleGlueControlPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
        - !GetAtt CreateRleGlueControlRole.Outputs.RoleName
      PolicyName: plc-inline-glue-controller
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'allowGlueAccess'
            Effect: 'Allow'
            Action:
              - 'glue:*'
            Resource:
              - '*'
          - Sid: 'allowCloudWatchAccess'
            Effect: 'Allow'
            Action:
              - 'cloudwatch:PutMetricData'
            Resource:
              - '*'              
          - Sid: 'allowLogAccess'
            Effect: 'Allow'
            Action:
              - 'logs:PutLogEvents'
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'           
            Resource:
              - '*'              
          - Sid: 'allowEventAccess'
            Effect: 'Allow'
            Action:
              - 'events:PutRule'
              - 'events:PutTargets'
              - 'events:RemoveTargets'
            Resource:
              - '*'
          - Sid: 'allowPassRole'
            Effect: 'Allow'
            Action:
              - "iam:PassRole"
            Resource:
              - !GetAtt CreateRleGlueControlRole.Outputs.RoleArn
            Condition:
              StringLike:
                "iam:PassedToService": "glue.amazonaws.com"
          - Sid: 'allowS3Access'
            Effect: 'Allow'
            Action:
              - "s3:ListBucket"
              - "s3:GetObject"
            Resource:
              - "arn:aws:s3:::*raw*/*"
              - "arn:aws:s3:::*raw*"
