AWSTemplateFormatVersion: 2010-09-09
Description: Lake Formation Access Controller Lambda for data lake as a service - Core (DaaS - Core)

Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, tst, int, qa, uat, prd, poc]
  LambdaZipFileName:
    Type: String
  AccountId:
    Type: String
    Default: XXXXXXXXXX

Resources:
  CreateDaaSLFAccessControllLambda:
    Type: 'AWS::CloudFormation::Stack'
    Properties :
      Parameters:
        Description: !Sub Datalake as a Service Lake Formation Access Controller deployed in ${Environment}
        Entity: !Ref Entity
        Environment: !Ref Environment
        HandlerName: ingest/lmd-ingest-lf-fgac.lambda_handler
        LambdaCompressedFileName: !Sub ${LambdaZipFileName}
        LambdaEnvVarFileName: !Sub stacks/stk-lmd-ingest-lf-fgac/stk-lmd-ingest-lf-fgac-env-var.yml
        MemorySize: 128
        Name: !Sub ${Entity}-lmd-ingest-lf-fgac-${Environment}        
        Timeout: 120
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-${Environment}/lmd/scripts/template/cft-lmd-common-template.yml
      TimeoutInMinutes : '60'

  CreateDaaSLFAccessControllPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
        - !GetAtt CreateDaaSLFAccessControllLambda.Outputs.LambdaRole
      PolicyName: plc-inline-lf-fgac
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "allowDaaSClientLFAssumeRole"
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Resource: 
              Fn::Sub: "arn:aws:iam::*:role/*-rle-ingest-lf-fgac-admin-${Environment}"
