AWSTemplateFormatVersion: 2010-09-09
Description: SQS ingestion queue for data lake as a service - core (DaaS - Core)

Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, tst, int, qa, uat, prd, poc]

Resources:
  CreateIngestSQSQueue:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Entity: !Ref Entity
        Environment: !Sub '${Environment}'
        EnableDLQ: true
        Name: !Sub '${Entity}-sqs-ingest-daas-core-${Environment}'
      TemplateURL: ../../daas-common/cft-sqs-common-template.yml
      TimeoutInMinutes: '60'

  CreateIngestSQSQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      Queues:
        - !GetAtt CreateIngestSQSQueue.Outputs.SQSQueueName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: SQSWriteaccess
            Effect: Allow
            Principal: '*'
            Action:
              - 'sqs:DeleteMessage'
              - 'sqs:ReceiveMessage'
              - 'sqs:SendMessage'
              - 'sqs:*'
            Resource:
              - !GetAtt CreateIngestSQSQueue.Outputs.S3QueueArn
            Condition:
              ArnLike:
                'aws:SourceArn': !Sub 'arn:aws:s3:::*-s3-${AWS::Region}-*-raw-*-${Environment}'
              StringEquals:
                'aws:PrincipalOrgID': !Ref OrganizationId

  OrganizationId:
      Type: 'AWS::CloudFormation::CustomResource'
      Properties:
        ServiceToken:
          Fn::ImportValue: !Sub ${Entity}-lmd-get-organization-id-${Environment}-ARN
