AWSTemplateFormatVersion: 2010-09-09
Description: Raw Metadata Purger Lambda for data lake as a service - Core

Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, tst, int, qa, uat, prd, poc]
  LambdaZipFileName:
    Type: String

Resources:
  CreateDaaSIngMetadataPurgeLambda:
    Type: 'AWS::CloudFormation::Stack'
    Properties :
      Parameters:
        Description: !Sub Datalake as a Service Core raw metadata purger deployed in ${Environment}
        Entity: !Ref Entity
        Environment: !Ref Environment
        HandlerName: ingest/lmd-ingest-metadata-purger.lambda_handler        
        LambdaCompressedFileName: !Sub ${LambdaZipFileName}
        MemorySize: 128
        Name: !Sub ${Entity}-lmd-ingest-metadata-purger-${Environment}        
        Timeout: 120
      TemplateURL: ../../daas-common/cft-lmd-common-template.yml
      TimeoutInMinutes : '60'

  CreateDaaSIngMetadataPurgePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
        - !GetAtt CreateDaaSIngMetadataPurgeLambda.Outputs.LambdaRole
      PolicyName: plc-inline-lmd-ingest-metadata-purge
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "assumeDaaSGlueControllerClientRole"
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Resource: 
              Fn::Sub: "arn:aws:iam::*:role/*-ingest-glue-controller-admin-${Environment}"