AWSTemplateFormatVersion: 2010-09-09
Description: Invoker Lambda for data lake as a service - core (DaaS - Core)

Parameters:
  Entity:
    Type: String
    Default: ganesh
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, tst, int, qa, uat, prd, poc]
  LambdaZipFileName:
    Type: String

Resources:
  CreateDaaSCoreInvkLambda:
    Type: 'AWS::CloudFormation::Stack'
    Properties :
      Parameters:
        Description: !Sub Lambda Invoker for Datalake as a Service deployed in ${Environment}
        Entity: !Ref Entity
        Environment: !Ref Environment
        HandlerName: ingest/lmd-ingest-invoker.lambda_handler
        LambdaCompressedFileName: !Sub ${LambdaZipFileName}
        LambdaEnvVarFileName: !Sub stacks/stk-lmd-ingest-invoker/stk-lmd-ingest-invoker-env-var.yml
        MemorySize: 128 
        Name: !Sub ${Entity}-lmd-ingest-invoker-${Environment}
        SqsEventTriggerArn: 
          Fn::ImportValue:
            !Sub "${Entity}-sqs-ingest-daas-core-${Environment}-arn"
        Timeout: 60
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${Entity}-s3-${AWS::AccountId}-${AWS::Region}-common-artifacts-${Environment}/lmd/scripts/template/cft-lmd-common-template.yml
      TimeoutInMinutes : '60'

  CreateDaaSMetadataInvkPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
        - !GetAtt CreateDaaSCoreInvkLambda.Outputs.LambdaRole
      PolicyName: plc-inline-lmd-ingest-invk
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "allowS3ReadAccess"
            Effect: "Allow"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
              - "s3:DeleteObjectVersion"
            Resource:
              - "*"
          -
            Sid: "allowStepFunctionAccess"
            Effect: "Allow"
            Action: "states:StartExecution"
            Resource:
              - "arn:aws:states:*:*:stateMachine:*"           